// Types
export type {
  UserRole,
  SiteCode,
  SiteFeatures,
  BankAccountInfo,
  Site,
  PaymentMethod,
  PaymentStatus,
  UserProfile,
  MenuItem,
  DeliveryMethod,
  OrderStatus,
  OrderItem,
  Order,
  QRExceptionToken,
  TimeGateStatus,
  WalletTransaction,
  PrinterConfig,
  AutoPrintConfig,
  BillType,
} from './types';

// Supabase client
export { supabase, isSupabaseConfigured } from './lib/supabase';

// API
export {
  login,
  signUp,
  logout,
  getSession,
  getCurrentUserProfile,
  getCachedUserProfile,
  setCachedUserProfile,
  getUsers,
  getCachedUsers,
  setCachedUsers,
  updateUserWallet,
  setUserDisabledStatus,
  getMenu,
  getAllMenuItems,
  getCachedMenu,
  setCachedMenu,
  DEFAULT_MENU_ITEMS,
  seedMenuToSupabase,
  createMenuItem,
  bulkCreateMenuItems,
  copyMenuBetweenSites,
  type CopyMenuOptions,
  updateMenuItem,
  placeOrder,
  cancelOrder,
  getOrders,
  getCachedOrders,
  setCachedOrders,
  updateOrderStatus,
  MONTHLY_WALLET_ALLOWANCE,
  fetchWalletTransactions,
  getLatestOrderStatus,
  getLatestMenuItemState,
  createUserByAdmin,
  approveUserAndFundWallet,
  fileToBase64,
  getCustomTimeGateConfig,
  fetchTimeGateConfig,
  setCustomTimeGateConfig,
  type TimeGateConfig,
  createQRToken,
  toggleQRTokenStatus,
  deleteQRToken,
  getQRTokens,
  getCachedQRTokens,
  setCachedQRTokens,
  getTimeGateStatus,
  subscribeRealtime,
  type RealtimeSyncInfo,
  broadcastSyncChannel,
  broadcastSystemEvent,
  supabaseGlobalSyncChannel,
  withQueryTimeout,
  parseItemsFromNote,
  getOrderDisplayItems,
  parseComboItem,
  isDrinkItem,
  getOrderTickets,
  getOrderBillRequirements,
  isOrderFullyPrinted,
  markBillPrinted,
  unmarkBillPrinted,
  type TicketType,
  type TicketItem,
  type OrderTicket,
  isValidUuid,
  generateUUID,
  AUTO_PRINT_STORAGE_KEY,
  getCustomAutoPrintConfig,
  fetchAutoPrintConfig,
  setAutoPrintEnabled,
  PRINTER_CONFIG_STORAGE_KEY,
  getCustomPrinterConfig,
  fetchPrinterConfig,
  setPrinterConfig,
  fetchOrderWithItems,
  mapOrder,
  DEFAULT_SITES,
  getSites,
  updateSite,
  confirmGuestPayment,
  rejectGuestPayment,
  subscribeGuestOrder,
  getVietQrBankCode,
  buildVietQrUrl,
  getSitePaymentQrUrl,
  downloadQrImage,
  isUuid,
  getCachedSites,
  setCachedSites,
  getSelectedSiteCode,
  setSelectedSiteCode,
  CURRENT_SITE_STORAGE_KEY,
} from './services/canteenApi';

// QZ Tray Multi-Printer POS Service
export {
  connectQz,
  disconnectQz,
  isQzConnected,
  listAvailablePrinters,
  buildEscPosCommands,
  printBillToPrinter,
  printTestTicket,
  printOrderToAllPrinters,
  renderTicketToCanvasImage,
  renderTestTicketToCanvasImage,
  removeVietnameseTones,
  printTicketAsImageToPrinter,
  ESC_POS_FEED_AND_CUT,
  type PrintBillResult,
  type MultiPrinterPrintResult,
  type AvailablePrintersResult,
} from './services/qzPrintService';

// Utils
export { detectCurrentDevice } from './utils/deviceDetector';
export type { DeviceInfo } from './utils/deviceDetector';
export { getTomorrowStr, getTodayStr, formatVnd } from './utils/date';
export {
  compressImage,
  extractStoragePath,
  formatBytes,
  type CompressImageOptions,
  type CompressResult,
} from './utils/imageCompressor';

