// Types
export type {
  UserRole,
  UserProfile,
  MenuItem,
  DeliveryMethod,
  OrderStatus,
  OrderItem,
  Order,
  QRExceptionToken,
  TimeGateStatus,
  WalletTransaction,
  PrinterConfig,
  AutoPrintConfig,
} from './types';

// Supabase client
export { supabase, isSupabaseConfigured } from './lib/supabase';

// API
export {
  login,
  signUp,
  logout,
  getSession,
  getCurrentUserProfile,
  getCachedUserProfile,
  setCachedUserProfile,
  getUsers,
  getCachedUsers,
  setCachedUsers,
  updateUserWallet,
  setUserDisabledStatus,
  getMenu,
  getAllMenuItems,
  getCachedMenu,
  setCachedMenu,
  DEFAULT_MENU_ITEMS,
  seedMenuToSupabase,
  createMenuItem,
  bulkCreateMenuItems,
  updateMenuItem,
  placeOrder,
  cancelOrder,
  getOrders,
  getCachedOrders,
  setCachedOrders,
  updateOrderStatus,
  getLatestOrderStatus,
  getLatestMenuItemState,
  createUserByAdmin,
  approveUserAndFundWallet,
  fileToBase64,
  getCustomTimeGateConfig,
  fetchTimeGateConfig,
  setCustomTimeGateConfig,
  type TimeGateConfig,
  createQRToken,
  toggleQRTokenStatus,
  deleteQRToken,
  getQRTokens,
  getCachedQRTokens,
  setCachedQRTokens,
  getTimeGateStatus,
  subscribeRealtime,
  type RealtimeSyncInfo,
  broadcastSyncChannel,
  broadcastSystemEvent,
  supabaseGlobalSyncChannel,
  withQueryTimeout,
  parseItemsFromNote,
  getOrderDisplayItems,
  parseComboItem,
  isDrinkItem,
  getOrderTickets,
  type TicketType,
  type TicketItem,
  type OrderTicket,
  isValidUuid,
  generateUUID,
  AUTO_PRINT_STORAGE_KEY,
  getCustomAutoPrintConfig,
  fetchAutoPrintConfig,
  setAutoPrintEnabled,
  PRINTER_CONFIG_STORAGE_KEY,
  getCustomPrinterConfig,
  fetchPrinterConfig,
  setPrinterConfig,
} from './services/canteenApi';

// QZ Tray Multi-Printer POS Service
export {
  connectQz,
  disconnectQz,
  isQzConnected,
  listAvailablePrinters,
  buildEscPosCommands,
  printBillToPrinter,
  printTestTicket,
  printOrderToAllPrinters,
  type PrintBillResult,
  type MultiPrinterPrintResult,
} from './services/qzPrintService';

// Utils
export { detectCurrentDevice } from './utils/deviceDetector';
export type { DeviceInfo } from './utils/deviceDetector';
export { getTomorrowStr, getTodayStr, formatVnd } from './utils/date';
export {
  compressImage,
  extractStoragePath,
  formatBytes,
  type CompressImageOptions,
  type CompressResult,
} from './utils/imageCompressor';

